/*
 * This source file was generated by the Gradle 'init' task
 */
package ham;

public class MainFrame {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
