/*
 * This source file was generated by the Gradle 'init' task
 */
package ham;

import javax.swing.SwingUtilities;

import ham.swing.frames.HAMFrame;;

public class MainFrame {
    @SuppressWarnings("unused")
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            HAMFrame hamFrame = new HAMFrame();
        });
    }
}
