/*
 * This source file was generated by the Gradle 'init' task
 */
package ham;

public class MainFrame {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new MainFrame().getGreeting());
    }
}
